Homework 05: Factor and figure management
================
Adam Mattsson
2018-10-17

[Return to Main Page](https://github.com/STAT545-UBC-students/hw05-mattsada)

-   [Factor Management](#factor-management)
    1.  [Drop Oceania](#drop-oceania)
    2.  [Reorder the levels of country or continent](#reorder-the-levels-of-country-or-continent)

    -   [Explore the effects of arrange](#explore-the-effects-of-arrange)

-   [File I/O](#file-io)
-   [Visualization design](#visualization-design)
-   [Writing figures to files](#writing-figures-to-files)

Load required packages (and suppress package startup messages):

Factor management
-----------------

With the data set of your choice, after ensuring the variable(s) you’re exploring are indeed factors, you are expected to: - Drop factor/levels - Reorder levels based on knowledge from data.

For this part of the assignment I chosed to work on the `gapminder` dataset, information on the Gapminder datset can be found [here](https://www.gapminder.org/).

### Drop Oceania

Filter the Gapminder data to remove observations associated with the `continent` of Oceania. Additionally, remove unused factor levels. Provide concrete information on the data before and after removing these rows and Oceania; address the number of rows and the levels of the affected factors.

First, lets see how many levels we have in the `continent` factor by calling `levels()` as such:

``` r
levels(gapminder$continent)
```

    ## [1] "Africa"   "Americas" "Asia"     "Europe"   "Oceania"

In total, there are 5 levels (Africa, Americas, Asia, Europe and Oceania) in the `continent` varaible. Now it's time to get rid of the "Oceania" level in the `continent` factor. This is achieved by filtering the dataset.

``` r
filtered.gapminder <- gapminder %>% 
  filter(continent != "Oceania" ) #remove all entries associated with Oceania
```

We can easily inspect the levels of the factors to see if we succesfully got rid of the Oceania data by utilizing the following chunk of code:

``` r
table(filtered.gapminder$continent) #print continent in table
```

    ## 
    ##   Africa Americas     Asia   Europe  Oceania 
    ##      624      300      396      360        0

As we can see we have sucesfully removed all the data from the Oceania level. However, the level is still present and we can remove this unused factor level by calling the following code:

``` r
filtered.gapminder.oceania <- droplevels(filtered.gapminder) #remove unsused levels
```

To inspect the factor once again we call the following code:

``` r
table(filtered.gapminder.oceania$continent) #print content in table
```

    ## 
    ##   Africa Americas     Asia   Europe 
    ##      624      300      396      360

All the data from the Oceania level has now been removed, as well the unused factor level. Just for comparison we can inspect the numbers of rows and levels of affected factors before and after removing Oceania from the Gapminder dataset, as such.

``` r
nrow(gapminder) #number of rows in original gapminder datset
```

    ## [1] 1704

``` r
nrow(filtered.gapminder.oceania) #number of rows in filtered gapminder datset
```

    ## [1] 1680

``` r
nrow(gapminder) - nrow(filtered.gapminder.oceania) #number of rows removed
```

    ## [1] 24

``` r
levels(gapminder$continent) #return the number of levels in the continent variable in original gapminder dataset
```

    ## [1] "Africa"   "Americas" "Asia"     "Europe"   "Oceania"

``` r
levels(filtered.gapminder.oceania$continent) #return the number of levels in the continent variable in filtered gapminder dataset
```

    ## [1] "Africa"   "Americas" "Asia"     "Europe"

In the orignal data set we had a total of 1704 observations (rows) and after filtering an d removing the Oceania level in `continent` variable we have 1680 observations (24 observations were removed in this filtering process). We can also see that the Oceania level has been successfully dropped by comparing the levels of each dataset.

### Reorder the levels of country or continent

Use the forcats package to change the order of the factor levels, based on a principled summary of one of the quantitative variables. Consider experimenting with a summary statistic beyond the most basic choice of the median.

For this task I'm presenting the range of GDP per capita for each country as my summary statistic. The top 10 countries are presented in the table bellow in descending order.

``` r
gap.gdp.range <- gapminder %>% 
  group_by(country) %>% #group by country
  summarize(continent = unique(continent), gdpPercap.Range = max(gdpPercap) - min(gdpPercap)) %>% #calculate summary statistics
  arrange(desc(gdpPercap.Range)) #arrange range in GDP per capita in descending order

knitr::kable(head(gap.gdp.range, n=10), 
             col.names = c('Country','Continent', 'GDP per capita ($)'), 
             align = 'c',
             format = 'html', 
             caption = "<h4>Ranges in GDP per capita: 1952-2007</h4>")
```

<table>
<caption>
<h4>
Ranges in GDP per capita: 1952-2007
</h4>
</caption>
<thead>
<tr>
<th style="text-align:center;">
Country
</th>
<th style="text-align:center;">
Continent
</th>
<th style="text-align:center;">
GDP per capita ($)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Kuwait
</td>
<td style="text-align:center;">
Asia
</td>
<td style="text-align:center;">
85404.70
</td>
</tr>
<tr>
<td style="text-align:center;">
Singapore
</td>
<td style="text-align:center;">
Asia
</td>
<td style="text-align:center;">
44828.04
</td>
</tr>
<tr>
<td style="text-align:center;">
Norway
</td>
<td style="text-align:center;">
Europe
</td>
<td style="text-align:center;">
39261.77
</td>
</tr>
<tr>
<td style="text-align:center;">
Hong Kong, China
</td>
<td style="text-align:center;">
Asia
</td>
<td style="text-align:center;">
36670.56
</td>
</tr>
<tr>
<td style="text-align:center;">
Ireland
</td>
<td style="text-align:center;">
Europe
</td>
<td style="text-align:center;">
35465.72
</td>
</tr>
<tr>
<td style="text-align:center;">
Austria
</td>
<td style="text-align:center;">
Europe
</td>
<td style="text-align:center;">
29989.42
</td>
</tr>
<tr>
<td style="text-align:center;">
United States
</td>
<td style="text-align:center;">
Americas
</td>
<td style="text-align:center;">
28961.17
</td>
</tr>
<tr>
<td style="text-align:center;">
Iceland
</td>
<td style="text-align:center;">
Europe
</td>
<td style="text-align:center;">
28913.10
</td>
</tr>
<tr>
<td style="text-align:center;">
Japan
</td>
<td style="text-align:center;">
Asia
</td>
<td style="text-align:center;">
28439.11
</td>
</tr>
<tr>
<td style="text-align:center;">
Netherlands
</td>
<td style="text-align:center;">
Europe
</td>
<td style="text-align:center;">
27856.36
</td>
</tr>
</tbody>
</table>
From this table, we can see that the country with the biggest range in GDP per capita is **Kuwait**. The large spread can possible be explained by the fact that some people made a huge fortune in exploiting resources such as oil, while others remained verry poor.

Here are some other useful ways in which you can reorder levels of a factor:

**Reordr continents by frequency**

``` r
t1 <- filtered.gapminder.oceania
t1$continent %>% 
  fct_infreq() %>% 
  levels()
```

    ## [1] "Africa"   "Asia"     "Europe"   "Americas"

**Reorder continent by median GDP per cap**

``` r
t1$continent %>% 
  fct_reorder(t1$gdpPercap) %>% 
  levels()
```

    ## [1] "Africa"   "Asia"     "Americas" "Europe"

**Flip order of GDP per capita for continents (descending order)**

``` r
t1$continent %>% 
  fct_reorder(t1$gdpPercap, .desc = TRUE) %>% 
  levels()
```

    ## [1] "Europe"   "Americas" "Asia"     "Africa"

#### Explore the effects of arrange

Does merely arranging the data have any effect on, say, a figure?

First, lets create a new dataset for this part of the assignment. We can create a new dataset from the original gapminder, lets say life expectancy for European countries in 2007.

``` r
t2 <- gapminder %>% 
  filter(year == 2007, continent == "Europe") %>% #filter to obtain entries for european countries in 2007
  select(year,lifeExp,country) #select variables

knitr::kable(head(t2, n = 10)) #print top 10 countries in Europe (2007) with highest lifeExp
```

|  year|  lifeExp| country                |
|-----:|--------:|:-----------------------|
|  2007|   76.423| Albania                |
|  2007|   79.829| Austria                |
|  2007|   79.441| Belgium                |
|  2007|   74.852| Bosnia and Herzegovina |
|  2007|   73.005| Bulgaria               |
|  2007|   75.748| Croatia                |
|  2007|   76.486| Czech Republic         |
|  2007|   78.332| Denmark                |
|  2007|   79.313| Finland                |
|  2007|   80.657| France                 |

If we want to arrange the lifeExp data in descending order we can call the `arrange()` function.

``` r
t2.arrange <- gapminder %>% 
  filter(year == 2007, continent == "Europe") %>% #filter to obtain entries for european countries in 2007
  select(year,lifeExp,country) %>% #select variables
  arrange(desc(lifeExp)) #arrange in descending order
knitr::kable(head(t2.arrange, n = 10)) #print top 10 European countries in 2007 with longest life expectancy in descending order
```

|  year|  lifeExp| country     |
|-----:|--------:|:------------|
|  2007|   81.757| Iceland     |
|  2007|   81.701| Switzerland |
|  2007|   80.941| Spain       |
|  2007|   80.884| Sweden      |
|  2007|   80.657| France      |
|  2007|   80.546| Italy       |
|  2007|   80.196| Norway      |
|  2007|   79.829| Austria     |
|  2007|   79.762| Netherlands |
|  2007|   79.483| Greece      |

We can then plot the two datasets and compare them.

``` r
ggplot(t2, aes(x = lifeExp, y = country)) + geom_point() + 
  labs(title = "Plot before arrangeing lifeExp in descending order")
```

![](hw05_files/figure-markdown_github/plot_gap_eur_2007_lifeexp-1.png)

``` r
ggplot(t2.arrange, aes(x = lifeExp, y = country)) + geom_point() + 
  labs(title = "Plot after arrangeing lifeExp in descending order")
```

![](hw05_files/figure-markdown_github/plot_gap_eur_2007_lifeexp_desc-1.png)

As we can see there is no difference in the two plots.

If we want to rearange the order factor levels (countries by lifeExp) we need to implement the `fct_reorder`function, as such:

``` r
ggplot(t2, aes(x = lifeExp, y = fct_reorder(country, lifeExp))) +
  geom_point()
```

![](hw05_files/figure-markdown_github/plot_gap_eur_2007_lifeexp_fct-1.png)

As we can observe in this last plot, the orders of the factor levels has been reordered and gives us a better visualization of the data. In other words, `arrange()` alone does not have any effect on the presented figures and the use of `forcats` package could help us in our task.

File I/O
--------

First, let's try the `write_csv` function and see how the data looks when we read it back into R. For now, I'll use a temporary folder using the `tempfile` argument.

``` r
tmp <- tempfile("gapg.gdp.range", fileext = ".csv") #create tmp 
write_csv(gap.gdp.range, tmp) #write reordered data to .csv
```

Now, let's read it back in!

``` r
csv <- read_csv(tmp) #read data back into R and store as new object
```

    ## Parsed with column specification:
    ## cols(
    ##   country = col_character(),
    ##   continent = col_character(),
    ##   gdpPercap.Range = col_double()
    ## )

Is the rearranged order intact? let's check.

``` r
knitr::kable(head(csv, n = 10))
```

| country          | continent |  gdpPercap.Range|
|:-----------------|:----------|----------------:|
| Kuwait           | Asia      |         85404.70|
| Singapore        | Asia      |         44828.04|
| Norway           | Europe    |         39261.77|
| Hong Kong, China | Asia      |         36670.56|
| Ireland          | Europe    |         35465.72|
| Austria          | Europe    |         29989.42|
| United States    | Americas  |         28961.17|
| Iceland          | Europe    |         28913.10|
| Japan            | Asia      |         28439.11|
| Netherlands      | Europe    |         27856.36|

The order seems to be intact. What about other valuble information such as the type of each variable?

``` r
str(csv)
```

    ## Classes 'tbl_df', 'tbl' and 'data.frame':    142 obs. of  3 variables:
    ##  $ country        : chr  "Kuwait" "Singapore" "Norway" "Hong Kong, China" ...
    ##  $ continent      : chr  "Asia" "Asia" "Europe" "Asia" ...
    ##  $ gdpPercap.Range: num  85405 44828 39262 36671 35466 ...
    ##  - attr(*, "spec")=List of 2
    ##   ..$ cols   :List of 3
    ##   .. ..$ country        : list()
    ##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
    ##   .. ..$ continent      : list()
    ##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
    ##   .. ..$ gdpPercap.Range: list()
    ##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
    ##   ..$ default: list()
    ##   .. ..- attr(*, "class")= chr  "collector_guess" "collector"
    ##   ..- attr(*, "class")= chr "col_spec"

``` r
str(gap.gdp.range) #summary of reshaped dataset before writing to csv
```

    ## Classes 'tbl_df', 'tbl' and 'data.frame':    142 obs. of  3 variables:
    ##  $ country        : Factor w/ 142 levels "Afghanistan",..: 72 114 96 56 63 7 135 58 67 91 ...
    ##  $ continent      : Factor w/ 5 levels "Africa","Americas",..: 3 3 4 3 4 4 2 4 3 4 ...
    ##  $ gdpPercap.Range: num  85405 44828 39262 36671 35466 ...

We can see that informations such as variable type has been lost when writng to .csv file. One thing we could do, if we want to save the data set in exactly the sme way as it is in our enviroment we can use the `saveRDS` and then load it with `readRDS`. Let's try that approach and compare them in the same way as we did with the csv approach.

``` r
tmp2 <- tempfile("gap.gdp.range", fileext = ".rds") #create tmp
saveRDS(gap.gdp.range, tmp2) #save as rds
rds <- readRDS(tmp2) #read rds into and store as new object for comparision
str(rds)
```

    ## Classes 'tbl_df', 'tbl' and 'data.frame':    142 obs. of  3 variables:
    ##  $ country        : Factor w/ 142 levels "Afghanistan",..: 72 114 96 56 63 7 135 58 67 91 ...
    ##  $ continent      : Factor w/ 5 levels "Africa","Americas",..: 3 3 4 3 4 4 2 4 3 4 ...
    ##  $ gdpPercap.Range: num  85405 44828 39262 36671 35466 ...

``` r
str(gap.gdp.range)
```

    ## Classes 'tbl_df', 'tbl' and 'data.frame':    142 obs. of  3 variables:
    ##  $ country        : Factor w/ 142 levels "Afghanistan",..: 72 114 96 56 63 7 135 58 67 91 ...
    ##  $ continent      : Factor w/ 5 levels "Africa","Americas",..: 3 3 4 3 4 4 2 4 3 4 ...
    ##  $ gdpPercap.Range: num  85405 44828 39262 36671 35466 ...

``` r
unique(rds == gap.gdp.range)
```

    ##      country continent gdpPercap.Range
    ## [1,]    TRUE      TRUE            TRUE

Nice, they're exactly the same and no information is lost/transformed.

Visualization design
--------------------

For this part of the task I decided to plot GDP per capita vs life expectancy in Scandinavian countries. The bubble size corresponds to the

``` r
bp <- gapminder %>%
  filter(country %in% c('Sweden', 'Denmark', 'Norway')) %>% 
  ggplot(aes(x = gdpPercap, y = lifeExp))+
  geom_point(aes(size = pop), pch = 21, show.legend = TRUE) +
  scale_size_continuous(range = c(2, 13)) +
  facet_wrap(~ country) +
  ylim(c(65,85)) +
  xlim(c(0,60000)) +
  aes(fill = country) +
  geom_smooth(method='loess',size=0.5, colour='black') + 
  labs(title = 'GDP per capita  vs life Expectancy in Scandinavia', x = 'GDP per capita', y = 'Life Expectancy', caption = 'Gapminder data') +
  theme_gdocs()
bp
```

![](hw05_files/figure-markdown_github/GDPperCap_vs_LifeExpectancy_Scandinavia-1.png)

Writing figures to files
------------------------

In order to write a figure to a file we can use the `ggsave()` function. we can also specify the diemensions of the output file in this function. The last part of this assignment is to embed the figure into the report. This is achieved by using `![Alt text](/path/to/img.png)`

``` r
ggsave("GDPperCap_vs_LifeExpectancy_Scandinavia.png",
  plot = bp, 
  device = "png",
  width = 10, 
  height = 7,
  dpi = 500)
```

![Alt text](GDPperCap_vs_LifeExpectancy_Scandinavia.png)
